# Generated by Django 3.0.4 on 2020-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='fb_likes',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='fb_likes',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fb_likes',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='no_of_users_voted',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
