# Generated by Django 3.0.4 on 2020-03-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20200318_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='no_of_users_voted',
            field=models.IntegerField(null=True),
        ),
    ]
