# Generated by Django 3.0.4 on 2020-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20200318_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='fb_likes',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='fb_likes',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fb_likes',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
